version: "3.9"

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
      network: host   # ⚠️ ESSENCIAL no seu ambiente
    image: landing-nuxt-2
    container_name: landing-nuxt-2
    ports:
      - "8080:80"
    restart: unless-stopped

